language: cpp

notifications:
  email:
    - amarburg@apl.washington.edu

# Per-OS configuration
matrix:
  env:
    - BUILD_TYPE=release
    - BUILD_DIR=build_ci
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

## Install OSX deps using a script
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install rake ; fi
  - rake dependencies:$TRAVIS_OS_NAME

script: rake debug:test release:test
